FrozenLake Env: https://github.com/openai/gym/blob/master/gym/envs/toy_text/frozen_lake.py
### ACTION:
LEFT = 0
DOWN = 1
RIGHT = 2
UP = 3

The episode ends when you reach the goal or fall in a hole.
You receive a reward of 1 if you reach the goal, and zero otherwise.

In it’s simplest implementation, Q-Learning is a table of values for every state (row) and action (column) possible in the environment. Within each cell of the table, we learn a value for how good it is to take a given action within a given state. In the case of the FrozenLake environment, we have 16 possible states (one for each block), and 4 possible actions (the four directions of movement), giving us a 16x4 table of Q-values. We start by initializing the table to be uniform (all zeros), and then as we observe the rewards we obtain for various actions, we update the table accordingly.

We make updates to our Q-table using something called the **Bellman equation**, which states that the expected long-term reward for a given action is equal to the immediate reward from the current action combined with the expected reward from the best future action taken at the following state. In this way, we reuse our own Q-table when estimating how to update our table for future actions!

Eq 1. Q(s,a) = r + γ(max(Q(s’,a’)) #mathematical optimization method known as dynamic programming.
https://en.wikipedia.org/wiki/Dynamic_programming

This says that the Q-value for a given state (s) and action (a) should represent the current reward (r) plus the maximum discounted (γ) future reward expected according to our own table for the next state (s’) we would end up in. The discount variable allows us to decide how important the possible future rewards are compared to the present reward. By updating in this way, the table slowly begins to obtain accurate measures of the expected future reward for a given action in a given state. 

In [20]:
import gym
import numpy as np

In [21]:
env = gym.make('FrozenLake-v0')

In [22]:
# 1.Initialize table with all zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])

In [23]:
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
# 2.Set learning parameters
lr = .8
y = .95
num_episodes = 2000

# 2.2. Create lists to contain total rewards and steps per episode
rList = []

## Observation / Next State from Env
### observation (object): 
an environment-specific object representing your observation of the environment. For example, pixel data from a camera, joint angles and joint velocities of a robot, or the board state in a board game.

### reward (float): 
amount of reward achieved by the previous action. The scale varies between environments, but the goal is always to increase your total reward.

### done (boolean): 
whether it’s time to reset the environment again. Most (but not all) tasks are divided up into well-defined episodes, and done being True indicates the episode has terminated. (For example, perhaps the pole tipped too far, or you lost your last life.)

### info (dict): 
diagnostic information useful for debugging. It can sometimes be useful for learning (for example, it might contain the raw probabilities behind the environment’s last state change). However, official evaluations of your agent are not allowed to use this for learning.


In [36]:
# 3. Implementation of Algorithm

# Iterates according to number of episodes
for i in range(num_episodes):
    # Reset Environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    # Implement Q-Table learning Algorithm
    while j < 99:
        j+=1
        # Choose an ACTION by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1, env.action_space.n) * (1./(i+1)))
        # Add Action to env and get new state, reward, done, and info
        s1, r, d, _ = env.step(a) # see obvservation above      
        #Update Q-Table with new knowlegde
        Q[s,a] = Q[s,a] + lr*(r + y * np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    rList.append(rAll)

In [37]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 3.983


In [38]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[2.74928548e-01 1.28901023e-02 1.26514465e-02 1.29843515e-02]
 [2.55839829e-03 1.53547422e-03 4.75396651e-04 2.88735461e-01]
 [1.88751414e-01 2.55194075e-03 2.76086197e-03 6.80162665e-03]
 [6.49424302e-03 6.56906143e-04 1.29428246e-03 6.80086295e-03]
 [2.72357862e-01 5.47987194e-03 2.13983294e-03 2.00756566e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.15775453e-04 1.41018123e-06 1.00982937e-01 1.79787314e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.85371367e-03 9.65445166e-03 1.24596374e-03 3.65588411e-01]
 [2.78400766e-03 4.53398239e-01 1.89449308e-04 5.72569412e-04]
 [6.26979979e-01 5.39193018e-04 5.90916612e-04 1.53977770e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.26216495e-01 0.00000000e+00]
 [0.00000000e+00 9.76666992e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.

In [31]:
env.action_space.n

4

In [39]:
print(rList)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 